Attempting to add the authentication strategy a local to my app
So that I can fix the air the following error.
Error: Unknown authentication strategy "local"
   at attempt (/root/expressLitter/node_modules/passport/lib/middleware/authenticate.js:166:37)
   at authenticate (/root/expressLitter/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at callbacks (/root/expressLitter/node_modules/express/lib/router/index.js:164:37)
   at param (/root/expressLitter/node_modules/express/lib/router/index.js:138:11)
   at pass (/root/expressLitter/node_modules/express/lib/router/index.js:145:5)
   at Router._dispatch (/root/expressLitter/node_modules/express/lib/router/index.js:173:5)
   at Object.router (/root/expressLitter/node_modules/express/lib/router/index.js:33:10)
   at next (/root/expressLitter/node_modules/express/node_modules/connect/lib/proto.js:169:15)
   at Immediate.<anonymous> (/root/expressLitter/node_modules/express/node_modules/connect/node_modules/express-session/index.js:377:7)
   at Immediate.immediate._onImmediate (timers.js:430:16)