Adding the missing view
Error: Failed to lookup view "account" in views directory "/root/expressLitter/views"
   at Function.app.render (/root/expressLitter/node_modules/express/lib/application.js:512:17)
   at ServerResponse.res.render (/root/expressLitter/node_modules/express/lib/response.js:828:7)
   at /root/expressLitter/app.js:84:7
   at callbacks (/root/expressLitter/node_modules/express/lib/router/index.js:164:37)
   at ensureAuthenticated (/root/expressLitter/app.js:116:39)
   at callbacks (/root/expressLitter/node_modules/express/lib/router/index.js:164:37)
   at param (/root/expressLitter/node_modules/express/lib/router/index.js:138:11)
   at pass (/root/expressLitter/node_modules/express/lib/router/index.js:145:5)
   at Router._dispatch (/root/expressLitter/node_modules/express/lib/router/index.js:173:5)
   at Object.router (/root/expressLitter/node_modules/express/lib/router/index.js:33:10)