Sessions variable does not exist.
Sessions don't exist yet, so I am assuming that adding express session to the configuration file  make sessions exist.
Fixing the following error:
TypeError: Cannot read property 'messages' of undefined
   at /root/expressLitter/app.js:9:61
   at callbacks (/root/expressLitter/node_modules/express/lib/router/index.js:164:37)
   at param (/root/expressLitter/node_modules/express/lib/router/index.js:138:11)
   at pass (/root/expressLitter/node_modules/express/lib/router/index.js:145:5)
   at Router._dispatch (/root/expressLitter/node_modules/express/lib/router/index.js:173:5)
   at Object.router (/root/expressLitter/node_modules/express/lib/router/index.js:33:10)
   at next (/root/expressLitter/node_modules/express/node_modules/connect/lib/proto.js:169:15)
   at Object.expressInit [as handle] (/root/expressLitter/node_modules/express/lib/middleware.js:30:5)
   at next (/root/expressLitter/node_modules/express/node_modules/connect/lib/proto.js:169:15)
   at Object.query [as handle] (/root/expressLitter/node_modules/express/node_modules/connect/lib/middleware/query.js:43:5)